In [8]:
import numpy as np
dataset_filename = "affinity_dataset.txt"
X = np.loadtxt(dataset_filename)

In [3]:
print(X[:5])

[[0. 0. 1. 1. 1.]
 [1. 1. 0. 1. 0.]
 [1. 0. 1. 1. 0.]
 [0. 0. 1. 1. 1.]
 [0. 1. 0. 0. 1.]]


In [10]:
num_apple_purchase = 0
for sample in X:
    if sample[3] == 1: # This person bought Apples
        num_apple_purchase += 1
print("{0} people bought Apples".format(num_apple_purchase))

36 people bought Apples
