In [4]:
import numpy as np
dataset_filename = "affinity_dataset.txt"
X = np.loadtxt(dataset_filename)

In [5]:
print(X[:5])

[[0. 0. 1. 1. 1.]
 [1. 1. 0. 1. 0.]
 [1. 0. 1. 1. 0.]
 [0. 0. 1. 1. 1.]
 [0. 1. 0. 0. 1.]]


In [6]:
num_apple_purchase = 0
for sample in X:
    if sample[3] == 1: # This person bought Apples
        num_apple_purchase += 1
print("{0} people bought Apples".format(num_apple_purchase))

36 people bought Apples


In [11]:
from collections import defaultdict
valid_rules = defaultdict(int)
invalid_rules = defaultdict(int)
num_occurances = defaultdict(int)

for sample in X:
    for premise in range(4):
        if sample[premise] == 0: continue
        num_occurances[premise] += 1
        for conclusion in range(4):
            if premise == conclusion: continue
            if sample[conclusion] == 1:
                valid_rules[(premise, conclusion)] += 1
            else:
                invalid_rules[(premise, conclusion)] += 1

support = valid_rules
confidence = defaultdict(int)
for premise, conclusion in valid_rules:
    rule = (premise, conclusion)
    confidence[rule] = valid_rules[rule] / num_occurances[premise]

def print_rule(premise, conclusion,
              support, confidence, features):
    premise_name = features[premise]
    conclusion_name = features[conclusion]
    print("Rule: if a person buys {0} they will also buy {1}".format(premise_name, conclusion_name))
    print(" - Support: {0}".format(support[(premise, conclusion)]))
    print(" - Confidence: {0:.3f}".format(confidence[(premise, conclusion)]))
    

In [12]:
premise = 1
conclusion = 3
print_rule(premise, conclusion, support, confidence, ['bread','milk','chess','apple','banana'])

Rule: if a person buys milk they will also buy apple
 - Support: 9
 - Confidence: 0.196
